### ISSUE TITLE
does not work with realvnc client nor tiger vnc client

### ISSUE THREAD

**Issue by phil123456** [gitbls/RPiVNCHowTo#5] opened 2021-04-06 12:00 UTC
Hi,

I tried both clients

 - real vnc client renders a black screen

 - tigervnc client cannot even connect on the box
downloaded here (https://www.tightvnc.com/download.php)

win 10-> raspberry pi 4

regards

**Comment by gitbls** [comment] 2021-04-06 13:29
Phil, how did you get make-systemd-xvnc to work, given your other report? Should I assume that you got past that issue?

I have tested both realvnc viewer and tightvnc viewer against these virtual VNC servers, and they all work. My guess is that you have not completed all the configuration correctly.

Please review the configuration documentation, and ensure that your system has been correctly and completely configured. If you are unable to get it working after this review, please respond with the following information and I'll work with you to get this resolved:

- What OS are you using?
- If RasPiOS, with the RasPiOS desktop, or Lite?
- What display manager are you using? (lightdm, xdm, or something else). 

One last thought. If your configuration edits are complete and correct, did you restart the system before trying to connect with a VNC viewer? This may be required to get the display manager to update its configuration.

Sounds like you're really close to having it working, and we'll get you there!

**Comment by phil123456** [comment] 2021-04-06 15:13
Raspbian

```
pi@raspberrypi:~/RPiVNCHowTo $ uname -a
Linux raspberrypi 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux
```

I followed your tutorial:

```
sudo apt-get remove realvnc-vnc-server

sudo nano /etc/lightdm/lightdm.conf

	[XDMCPServer]
	enabled=true
	port=177

sudo ./make-systemd-xvnc

	entered resolution for only one vnc socket : 1920x1080

sudo systemctl daemon-reload
```

I tried again, I get a black screen on tigervnc and realvnc client

also restarted many times

**Comment by gitbls** [comment] 2021-04-06 15:55
Please do `sudo journalctl -b` and copy and share here the log lines around the time of a failed connection.

I don't normally use lightdm, but if the logs you provide don't give me a good clue, I'll quickly/easily set up a test system to replicate. In order to do that, I'll need to know specifically which OS you're using...not the version number, but if it's RasPiOS, is it a desktop version or Lite?

**Comment by gitbls** [comment] 2021-04-07 13:22
I did a complete end-to-end test using Raspbian with Desktop and following the documentation on this github, and it worked correctly.

I did notice that after I enabled VNC socket, but had not configured lightdm that I could connect with VNC but only got a black screen. Once I edited lightdm.conf and restarted lightdm (which BTW logged me out, as expected), VNC worked correctly and completely.

Without technical evidence to the contrary, I can only conclude that you have not edited lightdm.conf correctly, or you did not restart lightdm (sudo systemctl restart lightdm) or reboot the system.

**Comment by gitbls** [comment] 2021-04-13 17:57
Since @phil123456 has not responded, and I have been unable to reproduce his issue except by not following the guide, I am going to close this issue. @phil123456, if you are able to provide additional details or a repro, please feel free to re-open this issue or open a new one so that we can resolve it.

**Closed as completed by gitbls** 2021-04-13 17:57 UTC
